import type { Metadata } from "next";
import { inter, fontMono, plusJakartaSans } from "@/lib/fonts";
import "../styles/globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </head>

      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased text-foreground",
          plusJakartaSans.variable
        )}
      >
        <nav className="sticky top-0 z-50">Home</nav>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
